on:
  push:
    branches:    
      - master
      
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
 
name: build-and-deploy-ahoi-attacks
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        
    - name: Build webapp
      run: |
        make init
        make build
  
